@startwbs PathFinder
*[#BlueViolet] PathFinder

**[#green] 1. Analyser les besoins du client (Product Owner)
***[#lightgreen] 1.1. Recueillir la description des besoins
***[#lightgreen] 1.2. Établir WBS, GANTT, PERT
***[#lightgreen] 1.3. Rédiger un rapport d'analyse initiale

**[#moccasin] 2. Analyser et itérer
***[#oldlace] 2.1. Définir le contexte du projet
***[#oldlace] 2.2. Créer le diagramme de cas d'utilisation
***[#oldlace] 2.3. Créer le diagramme de flux
***[#oldlace] 2.4. Réaliser les maquettes
***[#oldlace] 2.5. Identifier les personas
***[#oldlace] 2.6. Élaborer des storyboards
***[#oldlace] 2.7. Créer des wireframes
***[#oldlace] 2.8. Itérer sur les conceptions selon les retours
***[#oldlace] 2.9. Appliquer les principes S.O.L.I.D
***[#oldlace] 2.10. Réaliser des patrons de conception

**[#coral] 3. Développer les applications
***[#LightSalmon] 3.1. Créer une application WEB
***[#LightSalmon] 3.2. Créer une application Mobile
***[#LightSalmon] 3.3. Mettre en place un système de monitoring
***[#LightSalmon] 3.4. Configurer le réseau (Docker)
***[#LightSalmon] 3.5. Développer l'interface WebAdmin (Blazor)

**[#lightseagreen] 4. Concevoir la base de données
***[#mediumaquamarine] 4.1. Concevoir la structure de la base de données
***[#mediumaquamarine] 4.2. Établir MCD
***[#mediumaquamarine] 4.3. Établir MLD
***[#mediumaquamarine] 4.4. Mettre en place l'infrastructure ORM
***[#mediumaquamarine] 4.5. Créer les tables de la base de données
***[#mediumaquamarine] 4.6. Implémenter les données
***[#mediumaquamarine] 4.7. Concevoir l'API

**[#PaleVioletRed] 5. Tester le projet
***[#LightPink] 5.1. Mettre en place Sonar pour analyse de code
***[#LightPink] 5.2. Écrire et exécuter les tests unitaires
***[#LightPink] 5.3. Réaliser les tests fonctionnels
***[#LightPink] 5.4. Réaliser des tests utilisateurs

**[#SteelBlue] 6. Suivre le projet et rédiger les rapports
***[#LightBlue] 6.1. Produire des rapports périodiques légers
***[#LightBlue] 6.2. Évaluer le projet post-livraison
***[#LightBlue] 6.3. Livrer l'application finale (WEB et mobile)
@endwbs